#!/usr/bin/env python3
"""Tests for update-history.py.

Run with:  python3 -m unittest discover scripts

The converters are pure str -> str, so everything here runs offline against
small fixtures. The network fetch lives behind its own function and is not
exercised.
"""

import importlib.util
import pathlib
import unittest


def _load():
    """Import the hyphenated sibling module by path."""
    path = pathlib.Path(__file__).with_name("update-history.py")
    spec = importlib.util.spec_from_file_location("update_history", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


uh = _load()

DM32_URL = "https://technical.swissmicros.com/dm32/firmware/history.html"
VOY_URL = "https://technical.swissmicros.com/voyager/firmware/history.txt"
DMCP5 = uh.Platform("DMCP5", "../DMCP5_HISTORY.md",
                    "https://technical.swissmicros.com/dmcp/firmware_dmcp5/history.html")


def page(body):
    """Wrap a body fragment in the chrome every upstream page carries."""
    return (
        '<!DOCTYPE html>\n<html lang="en">\n<head>\n'
        '<title>Firmware History</title>\n'
        '<link rel="stylesheet" href="/mod_autoindex/style.css" type="text/css" />\n'
        "<style>\na { text-decoration: underline; }\n</style>\n"
        "</head>\n<body>\n"
        '<div class="header">\n<h1>DM32 Program Firmware History</h1>\n</div>\n'
        "<br/>\n"
        '<div class="highlighted">\n'
        "Please remember it is always wise to make FAT disk backup before any update.\n"
        "</div>\n<br/>\n<!-- Last changes here -->\n"
        + body +
        "\n</body>\n</html>\n"
    )


class HtmlDocumentShape(unittest.TestCase):

    def test_h1_becomes_title(self):
        out = uh.convert_html(page("<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>"), DM32_URL)
        self.assertTrue(out.startswith("# DM32 Program Firmware History\n"))

    def test_banner_names_the_source_url(self):
        out = uh.convert_html(page("<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>"), DM32_URL)
        self.assertIn("Generated by scripts/update-history.py", out)
        self.assertIn(DM32_URL, out)
        self.assertIn("Do not edit by hand", out)

    def test_highlighted_div_becomes_blockquote(self):
        out = uh.convert_html(page("<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>"), DM32_URL)
        self.assertIn(
            "> Please remember it is always wise to make FAT disk backup before any update.",
            out)

    def test_platform_link_emitted_when_given(self):
        out = uh.convert_html(page("<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>"),
                              DM32_URL, platform=DMCP5)
        self.assertIn("[DMCP5 system firmware history](../DMCP5_HISTORY.md)", out)
        self.assertIn(DMCP5.url, out)

    def test_no_platform_link_when_absent(self):
        out = uh.convert_html(page("<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>"), DM32_URL)
        self.assertNotIn("Platform firmware:", out)

    def test_noise_is_dropped(self):
        out = uh.convert_html(page(
            "<hr/>\n<p>&nbsp;</p>\n<br/>\n<h3>DM32 v2.11:  2025-12-05</h3>\n<p>&nbsp;</p>"),
            DM32_URL)
        for noise in ("<hr", "<br", "&nbsp;", "<style", "stylesheet",
                      "Last changes here", "<!DOCTYPE"):
            self.assertNotIn(noise, out)

    def test_output_is_deterministic(self):
        html = page("<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>\n"
                    '<div class="sub">Fixes</div>\n<ul><li>One</li></ul>')
        self.assertEqual(uh.convert_html(html, DM32_URL),
                         uh.convert_html(html, DM32_URL))

    def test_trailing_newline_exactly_one(self):
        out = uh.convert_html(page("<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>"), DM32_URL)
        self.assertTrue(out.endswith("\n"))
        self.assertFalse(out.endswith("\n\n"))


class HtmlReleaseHeadings(unittest.TestCase):

    def heading(self, h3):
        out = uh.convert_html(page("<hr/>\n<h3>%s</h3>" % h3), DM32_URL)
        return [ln for ln in out.splitlines() if ln.startswith("## ")]

    def test_plain_heading_uses_em_dash(self):
        self.assertEqual(self.heading("DM32 v2.11:  2025-12-05"),
                         ["## DM32 v2.11 — 2025-12-05"])

    def test_single_space_after_colon(self):
        self.assertEqual(self.heading("DM32 v2.03: 2023-06-15"),
                         ["## DM32 v2.03 — 2023-06-15"])

    def test_space_before_colon(self):
        self.assertEqual(self.heading("DM32 v2.02 : 2023-05-21"),
                         ["## DM32 v2.02 — 2023-05-21"])

    def test_keeps_built_with_parenthetical(self):
        self.assertEqual(self.heading("DM42n v3.26 (built with DMCP5 3.55): 2025-11-14"),
                         ["## DM42n v3.26 (built with DMCP5 3.55) — 2025-11-14"])

    def test_slash_date_normalises_to_iso(self):
        self.assertEqual(self.heading("DMCP v3.8 : 2018/07/03"),
                         ["## DMCP v3.8 — 2018-07-03"])

    def test_heading_without_model_name(self):
        self.assertEqual(self.heading("v3.0 : 2017/12/08"),
                         ["## v3.0 — 2017-12-08"])

    def test_trailing_whitespace_after_date(self):
        self.assertEqual(self.heading("DMCP v3.20: 2020-10-09 "),
                         ["## DMCP v3.20 — 2020-10-09"])

    def test_non_release_heading_passes_through(self):
        self.assertEqual(self.heading("End of Beta Phase"), ["## End of Beta Phase"])

    def test_upstream_typo_preserved_verbatim(self):
        self.assertEqual(self.heading("DM42 v3.10 (bult with DMCP 3.10): 2018-10-01"),
                         ["## DM42 v3.10 (bult with DMCP 3.10) — 2018-10-01"])


class HtmlSections(unittest.TestCase):

    def test_sub_div_becomes_h3(self):
        out = uh.convert_html(page(
            "<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>\n"
            '<div class="sub">Fixes</div>\n<ul><li>One</li></ul>'), DM32_URL)
        self.assertIn("### Fixes", out)

    def test_sub_label_is_free_text_not_an_enum(self):
        out = uh.convert_html(page(
            "<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>\n"
            '<div class="sub">User Manual updates in chapters</div>\n<ul><li>One</li></ul>'),
            DM32_URL)
        self.assertIn("### User Manual updates in chapters", out)

    def test_release_without_sub_label_emits_bullets_directly(self):
        out = uh.convert_html(page(
            "<hr/>\n<h3>DM42n v3.26 (built with DMCP5 3.55): 2025-11-14</h3>\n"
            "<ul>\n  <li>Upgrade Free42 core library to 3.3.10 version</li>\n</ul>"),
            DM32_URL)
        self.assertNotIn("###", out)
        lines = [ln for ln in out.splitlines() if ln.strip()]
        i = lines.index("## DM42n v3.26 (built with DMCP5 3.55) — 2025-11-14")
        self.assertEqual(lines[i + 1], "- Upgrade Free42 core library to 3.3.10 version")

    def test_unlabelled_bullets_then_labelled_section(self):
        out = uh.convert_html(page(
            "<hr/>\n<h3>DM42n v3.26 (built with DMCP5 3.55): 2025-11-14</h3>\n"
            "<ul>\n  <li>Upgrade Free42 core library</li>\n</ul>\n"
            '<div class="sub">DMCP5 changes</div>\n'
            "<ul>\n  <li>RESET+F4 activates bootloader (USB DFU)</li>\n</ul>"), DM32_URL)
        lines = [ln for ln in out.splitlines() if ln.strip()]
        self.assertLess(lines.index("- Upgrade Free42 core library"),
                        lines.index("### DMCP5 changes"))
        self.assertIn("- RESET+F4 activates bootloader (USB DFU)", lines)


class HtmlBullets(unittest.TestCase):

    def bullets(self, li):
        out = uh.convert_html(page(
            "<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>\n"
            '<div class="sub">Fixes</div>\n<ul>%s</ul>' % li), DM32_URL)
        return [ln for ln in out.splitlines() if ln.startswith("- ")]

    def test_anchor_becomes_markdown_link(self):
        self.assertEqual(
            self.bullets('<li>Fixed a crash '
                         '(<a href="https://forum.swissmicros.com/v.php?f=33&amp;t=4159">forum</a>)</li>'),
            ["- Fixed a crash ([forum](https://forum.swissmicros.com/v.php?f=33&t=4159))"])

    def test_bare_url_left_as_text(self):
        self.assertEqual(
            self.bullets("<li>Fixed div, mul (forum https://www.hpmuseum.org/forum/thread-24155.html)</li>"),
            ["- Fixed div, mul (forum https://www.hpmuseum.org/forum/thread-24155.html)"])

    def test_entities_are_unescaped(self):
        self.assertEqual(self.bullets("<li>STAT ERROR &amp; INVALID y^x</li>"),
                         ["- STAT ERROR & INVALID y^x"])

    def test_hard_wrapped_li_collapses_to_one_line(self):
        self.assertEqual(
            self.bullets("<li>Fixed: crash after using equation solver with Flag-11\n"
                         "(see the forum)</li>"),
            ["- Fixed: crash after using equation solver with Flag-11 (see the forum)"])

    def test_quotes_preserved(self):
        self.assertEqual(
            self.bullets('<li>improved glyphs in the SwissKeys font (the "bold" font).</li>'),
            ['- improved glyphs in the SwissKeys font (the "bold" font).'])


class VoyagerDocumentShape(unittest.TestCase):

    def test_title_and_banner(self):
        out = uh.convert_voyager("Firmware History\n\n\nV34: 2025-04-15\n  ALL: Tweak\n", VOY_URL)
        self.assertTrue(out.startswith("# Voyager Firmware History\n"))
        self.assertIn(VOY_URL, out)
        self.assertIn("Do not edit by hand", out)

    def test_output_is_deterministic(self):
        src = "Firmware History\n\nV34: 2025-04-15\n  ALL: Tweak\n"
        self.assertEqual(uh.convert_voyager(src, VOY_URL),
                         uh.convert_voyager(src, VOY_URL))

    def test_trailing_newline_exactly_one(self):
        out = uh.convert_voyager("Firmware History\n\nV34: 2025-04-15\n  ALL: Tweak\n", VOY_URL)
        self.assertTrue(out.endswith("\n"))
        self.assertFalse(out.endswith("\n\n"))


class VoyagerHeadings(unittest.TestCase):

    def heading(self, src):
        out = uh.convert_voyager("Firmware History\n\n" + src, VOY_URL)
        return [ln for ln in out.splitlines() if ln.startswith("## ")]

    def test_iso_date_kept(self):
        self.assertEqual(self.heading("V34: 2025-04-15\n  ALL: Tweak\n"),
                         ["## V34 — 2025-04-15"])

    def test_dotted_date_normalises_to_iso(self):
        self.assertEqual(self.heading("V32: 31.08.2021\n  ALL: Tweak\n"),
                         ["## V32 — 2021-08-31"])

    def test_unpadded_dotted_date_normalises_to_iso(self):
        self.assertEqual(self.heading("V8: 29.8.2012\n  ALL: Tweak\n"),
                         ["## V8 — 2012-08-29"])

    def test_trailing_colon_on_date_is_stripped(self):
        self.assertEqual(self.heading("V2: 21.2.2012:\n  ALL: Tweak\n"),
                         ["## V2 — 2012-02-21"])

    def test_trailing_whitespace_on_heading(self):
        self.assertEqual(self.heading("V30: 17.01.2020 \n  ALL: Tweak\n"),
                         ["## V30 — 2020-01-17"])

    def test_duplicate_version_numbers_both_kept(self):
        self.assertEqual(
            self.heading("V2: 22.3.2012\n  ALL: a\n\nV2: 14.3.2012\n  ALL: b\n"),
            ["## V2 — 2012-03-22", "## V2 — 2012-03-14"])

    def test_releases_keep_source_order(self):
        self.assertEqual(
            self.heading("V34: 2025-04-15\n  ALL: a\n\nV33: 2024-12-21\n  ALL: b\n"),
            ["## V34 — 2025-04-15", "## V33 — 2024-12-21"])


class VoyagerBodyShapes(unittest.TestCase):

    def body(self, src):
        out = uh.convert_voyager("Firmware History\n\n" + src, VOY_URL)
        head = out.index("## ")
        return [ln for ln in out[head:].splitlines() if ln.strip()]

    def test_model_block_becomes_h3_with_bullets(self):
        self.assertEqual(
            self.body("V34: 2025-04-15\n  DM1x:\n   - Default CPU speed is back to 12MHz\n"
                      "   - Fixed battery reading below 1.8V\n"),
            ["## V34 — 2025-04-15", "### DM1x",
             "- Default CPU speed is back to 12MHz",
             "- Fixed battery reading below 1.8V"])

    def test_inline_model_label_becomes_h3_with_single_bullet(self):
        self.assertEqual(
            self.body("V33: 2024-12-21\n  DM41: Corrected SETAF behavior\n"),
            ["## V33 — 2024-12-21", "### DM41", "- Corrected SETAF behavior"])

    def test_bare_items_emit_without_model_heading(self):
        self.assertEqual(
            self.body("V25: 18.01.2018\n  Fixed timing of alarm catalog listing\n"
                      "  Added X-mem module to DM41\n"),
            ["## V25 — 2018-01-18",
             "- Fixed timing of alarm catalog listing",
             "- Added X-mem module to DM41"])

    def test_bare_items_and_model_labels_mixed_in_one_release(self):
        self.assertEqual(
            self.body("V26: 25.03.2018\n  New bold 7-segment font (all DM1x models)\n"
                      "  DM41: Speed improvement\n"),
            ["## V26 — 2018-03-25",
             "- New bold 7-segment font (all DM1x models)",
             "### DM41", "- Speed improvement"])

    def test_same_model_label_twice_gets_two_headings(self):
        self.assertEqual(
            self.body("V33: 2024-12-21\n  DM16: New firmware version\n"
                      "  DM16: Enhanced SHOW HEX\n"),
            ["## V33 — 2024-12-21",
             "### DM16", "- New firmware version",
             "### DM16", "- Enhanced SHOW HEX"])


class VoyagerLabelRule(unittest.TestCase):
    """A colon does not make a model label. These are the traps in the source."""

    def body(self, src):
        out = uh.convert_voyager("Firmware History\n\nV26: 25.03.2018\n" + src, VOY_URL)
        head = out.index("## ")
        return [ln for ln in out[head:].splitlines() if ln.strip()]

    def test_bugfix_prefix_is_not_a_model(self):
        self.assertEqual(
            self.body("  Bugfix: MEM output fixed in DM15_M80 and DM15_M1B\n"),
            ["## V26 — 2018-03-25", "- Bugfix: MEM output fixed in DM15_M80 and DM15_M1B"])

    def test_gto_prefix_is_not_a_model(self):
        self.assertEqual(self.body("  GTO I: extended range to 999\n"),
                         ["## V26 — 2018-03-25", "- GTO I: extended range to 999"])

    def test_all_is_a_model_label(self):
        self.assertEqual(self.body("  ALL: Lowered consumption in serial console\n"),
                         ["## V26 — 2018-03-25", "### ALL", "- Lowered consumption in serial console"])

    def test_dmxx_is_a_model_label(self):
        self.assertEqual(self.body("  DMXX: Fixed julian date\n"),
                         ["## V26 — 2018-03-25", "### DMXX", "- Fixed julian date"])

    def test_slash_label_is_a_model_label(self):
        self.assertEqual(self.body("  DM15/16:\n   - New 2-line mode\n"),
                         ["## V26 — 2018-03-25", "### DM15/16", "- New 2-line mode"])

    def test_underscore_label_is_a_model_label(self):
        self.assertEqual(self.body("  DM15_M80: Change initial register allocation\n"),
                         ["## V26 — 2018-03-25", "### DM15_M80", "- Change initial register allocation"])

    def test_mixed_case_label_is_a_model_label(self):
        self.assertEqual(self.body("  DM1X: fixed PSE\n"),
                         ["## V26 — 2018-03-25", "### DM1X", "- fixed PSE"])

    def test_dash_separator_is_a_model_label(self):
        """V27 writes "DM41 - Fixed ..." instead of "DM41: Fixed ..."."""
        self.assertEqual(self.body("  DM41 - Fixed continuous stopwatch operation\n"),
                         ["## V26 — 2018-03-25", "### DM41",
                          "- Fixed continuous stopwatch operation"])

    def test_space_only_label_stays_bare_text(self):
        """V21 writes "DM1X fixed PSE" with no separator. Inferring a label there
        would be guesswork, so the line passes through intact."""
        self.assertEqual(
            self.body("  DM1X fixed PSE (keep any button pressed to interrupt)\n"),
            ["## V26 — 2018-03-25",
             "- DM1X fixed PSE (keep any button pressed to interrupt)"])

    def test_dash_inside_prose_is_not_a_label_split(self):
        self.assertEqual(
            self.body("  Changed init after reset - more battery friendly\n"),
            ["## V26 — 2018-03-25",
             "- Changed init after reset - more battery friendly"])


class VoyagerAnnotationsAndEscaping(unittest.TestCase):

    def test_removal_annotation_attaches_to_its_release(self):
        out = uh.convert_voyager(
            "Firmware History\n\n"
            "!!! V30 firmware was removed after confirmation of excessive consumption in OFF mode\n"
            "V30: 17.01.2020\n  ALL: Added 'bootloader' serial console command\n", VOY_URL)
        lines = [ln for ln in out.splitlines() if ln.strip()]
        i = lines.index("## V30 — 2020-01-17")
        self.assertEqual(
            lines[i + 1],
            "> !!! V30 firmware was removed after confirmation of excessive "
            "consumption in OFF mode")

    def test_asterisks_are_escaped(self):
        out = uh.convert_voyager(
            "Firmware History\n\nV16: 13.02.2014\n"
            "  *** this will be the last firmware version <32k ***\n", VOY_URL)
        self.assertIn(r"- \*\*\* this will be the last firmware version \<32k \*\*\*", out)

    def test_backtick_is_escaped(self):
        out = uh.convert_voyager("Firmware History\n\nV1: 10.2.2012\n  use `x` here\n", VOY_URL)
        self.assertIn(r"- use \`x\` here", out)

    def test_brackets_are_left_readable(self):
        out = uh.convert_voyager(
            "Firmware History\n\nV6: 1.7.2012\n"
            "  ALL: switch to 12MHz and back with [ON]+[9]\n", VOY_URL)
        self.assertIn("- switch to 12MHz and back with [ON]+[9]", out)


if __name__ == "__main__":
    unittest.main()


class HeadingsAreSeparated(unittest.TestCase):
    """Every heading needs a blank line above it, or Markdown renderers glue it
    to the preceding list."""

    def assert_headings_separated(self, out):
        lines = out.splitlines()
        for i, line in enumerate(lines):
            if line.startswith("#") and i > 0:
                self.assertEqual(
                    lines[i - 1], "",
                    "no blank line before %r (previous line %r)" % (line, lines[i - 1]))

    def test_voyager_block_then_next_model(self):
        out = uh.convert_voyager(
            "Firmware History\n\nV34: 2025-04-15\n"
            "  DM1x:\n   - Default CPU speed is back to 12MHz\n"
            "  DM16:\n   - Fixed internal RCL/STO calculation\n", VOY_URL)
        self.assert_headings_separated(out)

    def test_voyager_block_then_inline_label(self):
        out = uh.convert_voyager(
            "Firmware History\n\nV34: 2025-04-15\n"
            "  DM1x:\n   - Default CPU speed\n"
            "  DM41: Added Setup menu\n", VOY_URL)
        self.assert_headings_separated(out)

    def test_voyager_block_then_next_release(self):
        out = uh.convert_voyager(
            "Firmware History\n\nV34: 2025-04-15\n  DM1x:\n   - Speed\n"
            "\nV33: 2024-12-21\n  DM41: Fix\n", VOY_URL)
        self.assert_headings_separated(out)

    def test_voyager_bare_items_then_model(self):
        out = uh.convert_voyager(
            "Firmware History\n\nV26: 25.03.2018\n"
            "  New bold 7-segment font\n  DM41: Speed improvement\n", VOY_URL)
        self.assert_headings_separated(out)

    def test_html_bullets_then_sub_section(self):
        out = uh.convert_html(page(
            "<hr/>\n<h3>DM42n v3.26: 2025-11-14</h3>\n"
            "<ul><li>Upgrade Free42</li></ul>\n"
            '<div class="sub">DMCP5 changes</div>\n<ul><li>RESET+F4</li></ul>'), DM32_URL)
        self.assert_headings_separated(out)

    def test_html_bullets_then_next_release(self):
        out = uh.convert_html(page(
            "<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>\n<ul><li>One</li></ul>\n"
            "<hr/>\n<h3>DM32 v2.10:  2024-08-17</h3>\n<ul><li>Two</li></ul>"), DM32_URL)
        self.assert_headings_separated(out)


class HtmlMalformedMarkup(unittest.TestCase):
    """Upstream leaves <li> tags unclosed in places (DM42 has 155 <li> and 153
    </li>). Nothing may be dropped on the floor when that happens."""

    def bullets(self, body):
        out = uh.convert_html(page(
            "<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>\n" + body), DM32_URL)
        return [ln for ln in out.splitlines() if ln.startswith("- ")]

    def test_unclosed_li_followed_by_another_li(self):
        self.assertEqual(
            self.bullets("<ul><li>Fix: Crash in SHOW<li>Fix: INTEG_ down</li></ul>"),
            ["- Fix: Crash in SHOW", "- Fix: INTEG_ down"])

    def test_unclosed_li_at_end_of_list(self):
        self.assertEqual(self.bullets("<ul><li>PGMMENU patch</ul>"),
                         ["- PGMMENU patch"])

    def test_several_consecutive_unclosed_li(self):
        self.assertEqual(
            self.bullets("<ul><li>One<li>Two<li>Three</ul>"),
            ["- One", "- Two", "- Three"])

    def test_unclosed_li_before_a_sub_section(self):
        out = uh.convert_html(page(
            "<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>\n"
            "<ul><li>Register allocation patch</ul>\n"
            '<div class="sub">User Manual changes</div>\n'
            "<ul><li>Initial version</li></ul>"), DM32_URL)
        self.assertIn("- Register allocation patch", out.splitlines())
        self.assertIn("### User Manual changes", out.splitlines())
        self.assertIn("- Initial version", out.splitlines())

    def test_unclosed_li_before_next_release_heading(self):
        out = uh.convert_html(page(
            "<hr/>\n<h3>DM32 v2.11:  2025-12-05</h3>\n<ul><li>Kept item\n"
            "<hr/>\n<h3>DM32 v2.10:  2024-08-17</h3>\n<ul><li>Later item</li></ul>"),
            DM32_URL)
        lines = out.splitlines()
        self.assertIn("- Kept item", lines)
        self.assertIn("- Later item", lines)
        self.assertLess(lines.index("- Kept item"), lines.index("## DM32 v2.10 — 2024-08-17"))
